import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // 指南：定位、架构总览与快速开始
  gettingStartedSidebar: [
    {type: 'autogenerated', dirName: 'getting-started'},
  ],

  // 规范：目录、编码、接口设计规范
  specificationSidebar: [
    {type: 'autogenerated', dirName: 'specification'},
  ],

  // 功能设计：WebSocket、SSE、GraphQL、认证授权、安全与周边能力
  featuresSidebar: [
    {type: 'autogenerated', dirName: 'features'},
  ],

  // 微服务集成：网关接入、服务间通信、可观测性
  integrationSidebar: [
    {type: 'autogenerated', dirName: 'integration'},
  ],

  // 流水线：Lint、测试、CI/CD、部署
  pipelineSidebar: [
    {type: 'autogenerated', dirName: 'pipeline'},
  ],

  // 参考：配置手册、平台差异、性能
  referenceSidebar: [
    {type: 'autogenerated', dirName: 'reference'},
  ],
};

export default sidebars;
